# Generated by Django 3.2.12 on 2023-06-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents_percentage', models.FloatField(default=0)),
                ('images_percentage', models.FloatField(default=0)),
                ('music_percentage', models.FloatField(default=0)),
                ('videos_percentage', models.FloatField(default=0)),
            ],
        ),
    ]
