# Generated by Django 3.2.12 on 2023-06-17 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_rename_is_favorite_music_is_starred'),
        ('starred', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarredMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music')),
            ],
        ),
    ]
