# Generated by Django 3.2.12 on 2023-06-17 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_rename_is_favorite_images_is_starred'),
        ('starred', '0002_starredmusic'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarredImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.images')),
            ],
        ),
    ]
