# Generated by Django 3.2.12 on 2023-06-17 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_videos_id'),
        ('starred', '0003_starredimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarredVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.videos')),
            ],
        ),
    ]
