# Generated by Django 3.2.12 on 2023-06-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starred', '0004_starredvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Starred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_starred', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='starredimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='starredmusic',
            name='music',
        ),
        migrations.RemoveField(
            model_name='starredvideo',
            name='video',
        ),
        migrations.DeleteModel(
            name='StarredDocument',
        ),
        migrations.DeleteModel(
            name='StarredImage',
        ),
        migrations.DeleteModel(
            name='StarredMusic',
        ),
        migrations.DeleteModel(
            name='StarredVideo',
        ),
    ]
