# Generated by Django 3.2.12 on 2023-06-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locked', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locked',
            name='file',
            field=models.FileField(null=True, upload_to='locked/'),
        ),
        migrations.AddField(
            model_name='locked',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locked',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
