# Generated by Django 3.2.12 on 2023-06-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='is_favorite',
            new_name='is_starred',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
