# Generated by Django 3.2.12 on 2023-06-17 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_images_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='is_favorite',
            new_name='is_starred',
        ),
    ]
